# Generated by Django 3.1.2 on 2020-10-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201011_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='changed_version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
