# Generated by Django 3.1.2 on 2020-10-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201011_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changes',
            name='changed_version',
        ),
    ]
