# Generated by Django 3.1.2 on 2020-10-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_changes_changed_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changes',
            name='id',
        ),
        migrations.AlterField(
            model_name='changes',
            name='changed_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.note'),
        ),
    ]
