# Generated by Django 3.1.2 on 2020-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201011_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='changed_version',
            field=models.IntegerField(default=1),
        ),
    ]
