# Generated by Django 3.1.2 on 2020-10-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201011_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Changes',
            new_name='ChangesNotes',
        ),
    ]
