# Generated by Django 3.1.2 on 2020-10-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201011_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChangesNotes',
            new_name='Changes',
        ),
    ]
