# Generated by Django 3.1.2 on 2020-10-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201011_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='changed_content',
            field=models.TextField(default='no changed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changes',
            name='changed_title',
            field=models.CharField(default='no changed', max_length=50),
            preserve_default=False,
        ),
    ]
