# Generated by Django 3.1.2 on 2020-10-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201011_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changes',
            old_name='changed_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='changes',
            old_name='changed_title',
            new_name='title',
        ),
    ]
