# Generated by Django 3.1.2 on 2020-10-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201011_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changes',
            old_name='changed_version',
            new_name='version',
        ),
    ]
