# Generated by Django 3.1.2 on 2020-10-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201011_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalNote',
        ),
    ]
