# Generated by Django 3.1.2 on 2020-10-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_historicalnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='changed_note',
            field=models.IntegerField(),
        ),
    ]
